zookeeper:
  image: infynyxx/zookeeper
  ports:
    - "49181:2181"
    - "22"
nimbus:
  image: infynyxx/storm-nimbus
  ports:
    - "49773:3773"
    - "49772:3772"
    - "49627:6627"
    - "22"
  links:
    - zookeeper:zk
supervisor:
  image: infynyxx/storm-supervisor
  ports:
    - "8000"
    - "22"
  links:
    - nimbus:nimbus
    - zookeeper:zk
ui:
  image: infynyxx/storm-ui
  ports:
    - "49080:8080"
    - "22"
  links:
    - nimbus:nimbus
    - zookeeper:zk

kafka:
  image: infynyxx/kafka
  ports:
    - "9092"
  links:
    - zookeeper:zk
  environment:
    KAFKA_ADVERTISED_HOST_NAME: 192.168.59.103
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
