zookeeper:
  image: infynyxx/zookeeper
  ports:
    - "49181:2181"
    - "22"

mysql:
  build: druid-mysql
  environment:
    - MYSQL_ROOT_PASSWORD=doesntreallymatter
    - MYSQL_USER=druid
    - MYSQL_PASSWORD=diurd
    - MYSQL_DATABASE=druid

nimbus:
  image: infynyxx/storm-nimbus
  ports:
    - "49773:3773"
    - "49772:3772"
    - "49627:6627"
    - "22"
  links:
    - zookeeper:zk
supervisor:
  image: infynyxx/storm-supervisor
  ports:
    - "8000"
    - "22"
  links:
    - nimbus:nimbus
    - zookeeper:zk
ui:
  image: infynyxx/storm-ui
  ports:
    - "49080:8080"
    - "22"
  links:
    - nimbus:nimbus
    - zookeeper:zk

kafka:
  image: infynyxx/kafka
  ports:
    - "9092"
  links:
    - zookeeper:zk
  environment:
    KAFKA_ADVERTISED_HOST_NAME: 192.168.59.103
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock  

druidcoordinator:
  build: druid
  command: coordinator
  links:
    - zookeeper:zk
    - mysql:mysql
  ports:
    - 80:8000
  environment:
    - MYSQL_ROOT_PASSWORD=doesntreallymatter
    - MYSQL_USER=druid
    - MYSQL_PASSWORD=diurd
    - MYSQL_DATABASE=druid

druidhistorical:
  build: druid
  command: historical
  links:
    - zookeeper:zk
  ports:
    - 8000
  environment:
    - s3_access_key=yolo
    - s3_secret_key=yolo
    - s3_bucket=nomi-druid-dev

druidbroker:
  build: druid
  command: broker
  ports:
    - 8000
  links:
    - zookeeper:zk

druidoverlord:
  build: druid
  command: overlord
  links:
    - zookeeper:zk
    - mysql:mysql
  ports:
    - 8000
  environment:
    - JAVA_MEMORY=5g
